version: "3.7"
services:
  mysql_db:
    container_name: sqlserver
    image: "mysql:8.0"
    restart: always
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
  practiceproject:
    container_name: appcontainer
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/app