version: "3"
services:
  mysql:
    container_name: sqlserver
    image: "mysql:8.0"
    restart: always
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  practicepr:
    container_name: appcontainer
    image: practiceproject
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app
  spabackend:
    container_name: spab
    image: spaback
    ports:
      - 8060:8080
    depends_on:
      - mysql
  spafrontend:
    container_name: spaf
    image: spafront
    ports:
      - 4200:80