name: PracticeProject
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  container-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          DB_DATABASE: test
          DB_USER: user
          DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set up MySQL
        run: |
              sudo /etc/init.d/mysql start
              mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Build and Test with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Test Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}