name: PracticeProject

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQLServer1
        uses: mirromutth/mysql-action@v1.1
        with:
          container port: '3307'
          mysql version: '8.0'
          mysql database: 'app_test'
          host port: '3308'
          mysql root password: 'password'
          mysql user: 'user'
          mysql password: 'password'
      - name: Set up MySQLServer2
        uses: mirromutth/mysql-action@v1.2
        with:
          container port: '3308'
          mysql version: '8.0'
          mysql database: 'app'
          host port: '3307'
          mysql root password: 'password'
          mysql user: 'user'
          mysql password: 'password'
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B package --file pom.xml